spring:
  application:
    name: lm-issues
  datasource:
    url: jdbc:postgresql://localhost:5432/lamuralla
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB
server:
  port: 8080
file:
  upload-dir: C:/Users/Diego/Desktop/description-uploads
  upload-access-url: http://localhost:8080/description-uploads/
app:
  cors:
    allowed-origins: http://localhost:3000
    allowed-origins-patterns: https://*.cartagenacorporation.com
  jwt:
    secret: ${JWT_SECRET}
auth:
  service:
    url: http://localhost:8081/api/oauth
project:
  service:
    url: http://localhost:8082/api/projects
sprint:
  service:
    url: http://localhost:8089/api/sprints
audit:
  service:
    url: http://localhost:8083/api/audit
notification:
  service:
    url: http://localhost:8086/api/notifications
