spring:
  application:
    name: lm-issues
  datasource:
    url: jdbc:postgresql://localhost:5432/lamuralla
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: 'false'
app:
  cors:
    allowed-origins: http://localhost:3000
  jwt:
    secret: ${JWT_SECRET}
auth:
  service:
    url: http://localhost:8081/api/oauth
project:
  service:
    url: http://localhost:8082/api/projects
sprint:
  service:
    url: http://localhost:8089/api/sprints
audit:
  service:
    url: http://localhost:8083/api/audit
notification:
  service:
    url: http://localhost:8086/api/notifications
comment:
  service:
    url: http://localhost:8084/api/comments